<?php

namespace Oyova\WpSupport\Acf\Blocks;

use WP_Block_Supports;

class Block {
	public $block = null;

	public function __construct( array $block ) {
		$this->block = $block;
	}

	public function get_element_open(): string {
		$type = $this->get_element_type();

		return oyo_format_string(
			'<!type id=":id" class=":class" style=":style">',
			array(
				'!type'  => $type,
				':id'    => $this->get_element_id(),
				':class' => $this->get_element_class(),
				':style' => $this->get_element_style(),
			)
		);
	}

	public function get_element_close(): string {
		$type = $this->get_element_type();

		return oyo_format_string(
			'</!type>',
			array(
				'!type' => $type,
			)
		);
	}

	public function get_element_class(): string {
		return implode( ' ', $this->get_classes() );
	}

	public function get_element_style(): string {
		return implode( ';', $this->get_styles() );
	}

	public function get_element_id(): string {
		return $this->block['anchor'] ?? '';
	}

	public function get_element_type() {
		if ( ! isset( $this->block['element_type'] ) ) {
			return 'div';
		}

		if ( ! is_string( $this->block['element_type'] ) ) {
			return 'div';
		}

		if ( ! ctype_alpha( $this->block['element_type'] ) ) {
			return 'div';
		}

		return $this->block['element_type'];
	}

	public function get_styles(): array {
		$styles = array();

		if ( isset( $this->block['user_style'] ) ) {
			$styles[] = $this->block['user_style'];
		}

		return array_merge(
			$styles,
			$this->get_wp_styles(),
		);
	}

	public function get_classes(): array {
		$classes      = array();
		$user_classes = array();
		$wp_class     = $this->get_wp_class();

		$classes[] = 'c-' . sanitize_title( $this->block['title'] );

		if ( isset( $this->block['user_class'] ) && is_array( $this->block['user_class'] ) ) {
			$classes = array_merge( $classes, $this->block['user_class'] );
		}

		return array_merge(
			$classes,
			$wp_class
		);
	}

	public function get_wp_styles(): array {
		$styles = array();

		// gets all attributes generated by block supports, including class, style.
		$attributes = WP_Block_Supports::get_instance()->apply_block_supports();

		if ( isset( $attributes['style'] ) ) {
			$styles[] = $attributes['style'];
		}

		return $styles;
	}

	public function get_wp_class(): array {
		$class = array();

		if ( isset( $this->block['className'] ) ) {
			$class[] = $this->block['className'];
		}

		return $class;
	}
}
